# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
    - libgpgme11-dev
    - libsodium-dev
latex: false
pandoc_version: 1.17.2
warnings_are_errors: false
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = T)'
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check --no-build-vignettes --no-manual  *tar.gz
  - Rscript -e 'devtools::install(pkg = ".")'
before_script:
  - chmod +x ./builddocs.sh
script:
  - ./builddocs.sh
